from collections import deque

def calculate_parallel_deployment(deps, num_serv):
    total_steps = 0
    #prepare info
    map_dependencies = {} #num_service, [dependencies]

    for i in range(num_serv):
        map_dependencies[i] = (i, set())

    for d in deps:
        map_dependencies[d[0]][1].add(d[1])

    #add initial non dependent services to the queue
    q = deque()
    for id_dep in map_dependencies.keys():
        if len(map_dependencies[id_dep][1]) == 0:
            q.append(id_dep)

    total_steps = 1
    while len(q) > 0:
        idserv = q.popleft()
        map_dependencies.pop(idserv)

        removed = False
        for key in map_dependencies.keys():
            if len(map_dependencies[key]) > 0 and idserv in map_dependencies[key][1]:
                map_dependencies[key][1].remove(idserv)
                if len(map_dependencies[key][1]) == 0:
                    q.append(key)
                    removed = True
        if removed:
            total_steps += 1

    if len(q) > 0 or len(map_dependencies) > 0:
        return -1

    return total_steps





if __name__ == '__main__':
    print("Start of the program")

    testCases = [
        ([[1, 0], [2, 0], [3, 1], [3, 2], [4, 3]], 5, 4),
        ([[1, 0], [2, 1], [0, 2]], 3, -1),
        ([[1, 0], [2, 0], [3, 0]], 4, 2),
        ([[1, 0], [2, 0], [3, 0], [4,3]], 5, 3)
    ]

    for services, k, expected in testCases:
        result = calculate_parallel_deployment(services, k)
        if result == expected:
            print("Pass", services, k, result)
        else:
            print("Fail", services, k, result, expected)

'''
Challenge 2: Distributed Data Sync Optimization (Graph / Topological Sort)
Problem StatementYou are deploying a set of microservices in an
IBM Cloud environment. Certain services depend on data generated by other
services. You are given a list of services and a list of dependencies
where dependencies[i] = [A, B] means service A requires service B
to complete its data synchronization before A can boot.
Additionally, some crucial core services are marked as CRITICAL.
Compute the maximum parallel boot steps required to start all services.
If there is a cyclic dependency rendering deployment impossible, return -1.
Constraints
1 <= services <= 10^5
0 <= dependencies <= 10^5

Solution Idea
This is a classic variation of Kahn's Algorithm for Topological
Sort using a Breadth-First Search (BFS) approach tracking the
layers (or depth) of parallel execution.


Challenge 2: Distributed Data Sync Optimization
This sample tracks dependencies to see how many "waves" or layers of parallel boots are needed, as well as checking for circular roadblocks.

Case A: Valid Parallel Deployment
Input: num_services = 5, dependencies = [[1, 0], [2, 0], [3, 1], [3, 2], [4, 3]]

Output: 4

Explanation: * Step 1: Service 0 has no dependencies and boots first.

Step 2: Services 1 and 2 depend only on 0, so they boot in parallel.

Step 3: Service 3 depends on both 1 and 2, so it boots next.

Step 4: Service 4 depends on 3 and boots last.
Total depth = 4 steps.

Case B: Cyclic Dependency (Deadlock)
Input: num_services = 3, dependencies = [[1, 0], [2, 1], [0, 2]]

Output: -1

Explanation: Service 0 waits for 2, 2 waits for 1, and 1 waits for 0. Nothing can boot.


'''
